### ISSUE TITLE
Failing `main` and `module` reference

### ISSUE THREAD

**Issue by christian-bromann** [lionel87/shrink-path#3]
Mind updating the references to `main` and `module` from 
```json
  "main": "./cjs/index.js",
  "module": "./esm/index.js",
```

to

```json
  "main": "cjs/index.js",
  "module": "esm/index.js",
```

I don't know why but the leading `./` causes issues with rollup.

**Comment by lionel87** [comment]
Removed the dot, please check if problem still persists with version `0.3.1`.

**Comment by christian-bromann** [comment]
Works perfect, thanks! 👍
